maximum:
  length_name: 50
  length_email: 255
minimum:
  length_pass: 6
image:
  big_size: 120
  small_size: 40
  comment_size: 25
  icon_size: 20
page:
  child_in_page: 5
notify:
  max_notify_show: 5
comment:
  comment_show: 2
info:
  email: "henchiyb@gmail.com"
  phone: "0942298558"
  address: "HTP Building Tran Khat Chan"
resize:
  to_fill_1: 118
  to_fill_2: 100
  to_limit: 800
