maximum:
  length_name: 50
  length_email: 255
minimum:
  length_pass: 6
image:
  big_size: 80
  small_size: 40
  comment_size: 25
page:
  child_in_page: 5
notify:
  max_notify_show: 5
comment:
  comment_show: 2
